name: Deploy to Oracle Server

on: workflow_dispatch
  # push:
  #   branches: ['main']
  #   paths: ['backend/**']
  # pull_request:
  #   branches: ['main']
  #   paths: ['backend/**']

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create VENV
        run: python3 -m virtualenv backend/flaskenv
      - name: Activate VENV
        run: source backend/flaskenv/bin/activate
      - name: Install Packages
        run: $(pwd)/backend/flaskenv/bin/pip3 install -r backend/requirements.txt
      - name: Chmod Script
        run: sudo chmod +x backend/add-ini-wsgi-conf.sh
      - name: Run Script
        run: sudo ./backend/add-ini-wsgi-conf.sh flask.ini flask.sock
      - name: Test Action
        run: echo "TEST Success"
